### ISSUE TITLE
No bundle URL present

### ISSUE THREAD

**Issue by anhtuank7c** [lelandrichardson/native-navigation-boilerplate#1]
I follow 3 steps, but failed to run.
```
git clone https://github.com/lelandrichardson/native-navigation-boilerplate.git
cd native-navigation-boilerplate
npm install
```

Error: No bundle URL present

![screen shot 2017-03-16 at 10 02 54 am](https://cloud.githubusercontent.com/assets/3163410/23980039/d151df94-0a2f-11e7-8214-05de94d9c320.png)

**Comment by nak1b** [comment]
run npm start in different terminal

**Comment by anhtuank7c** [comment]
@nak1b Thank you
